# Generated by Django 4.1.2 on 2022-10-26 16:57

from django.db import migrations, models
import expenses.validators


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="money",
            field=models.IntegerField(
                default=100, validators=[expenses.validators.validate_money]
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="money",
            field=models.IntegerField(
                default=1, validators=[expenses.validators.validate_money]
            ),
        ),
    ]
